######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 1 20:34:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stable.h util.h
SOURCES += main.cpp util.cpp
