######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 24 18:13:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

PRECOMPILED_HEADER = stable.h

CONFIG += qt

# Input
HEADERS += stable.h \
           util.h
SOURCES += main.cpp \
           util.cpp
